/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.16.3 on Thu Sep 18 06:18:33 2014
 *
 * Copyright (c) 2014 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt5.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtWidgets.h"

#line 26 "C:\\Users\\marcus\\Downloads\\PyQt-gpl-5.3.2\\sip/QtWidgets/qgraphicsgridlayout.sip"
#include <qgraphicsgridlayout.h>
#line 29 "C:\\Users\\marcus\\Downloads\\PyQt-gpl-5.3.2\\QtWidgets/sipQtWidgetsQGraphicsGridLayout.cpp"

#line 26 "C:\\Users\\marcus\\Downloads\\PyQt-gpl-5.3.2\\sip/QtWidgets/qgraphicslayoutitem.sip"
#include <qgraphicslayoutitem.h>
#line 33 "C:\\Users\\marcus\\Downloads\\PyQt-gpl-5.3.2\\QtWidgets/sipQtWidgetsQGraphicsGridLayout.cpp"
#line 101 "sip/QtCore/qsize.sip"
#include <qsize.h>
#line 36 "C:\\Users\\marcus\\Downloads\\PyQt-gpl-5.3.2\\QtWidgets/sipQtWidgetsQGraphicsGridLayout.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 39 "C:\\Users\\marcus\\Downloads\\PyQt-gpl-5.3.2\\QtWidgets/sipQtWidgetsQGraphicsGridLayout.cpp"
#line 165 "sip/QtCore/qrect.sip"
#include <qrect.h>
#line 42 "C:\\Users\\marcus\\Downloads\\PyQt-gpl-5.3.2\\QtWidgets/sipQtWidgetsQGraphicsGridLayout.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 45 "C:\\Users\\marcus\\Downloads\\PyQt-gpl-5.3.2\\QtWidgets/sipQtWidgetsQGraphicsGridLayout.cpp"
#line 26 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 48 "C:\\Users\\marcus\\Downloads\\PyQt-gpl-5.3.2\\QtWidgets/sipQtWidgetsQGraphicsGridLayout.cpp"
#line 30 "C:\\Users\\marcus\\Downloads\\PyQt-gpl-5.3.2\\sip/QtWidgets/qgraphicsitem.sip"
#include <qgraphicsitem.h>
#line 51 "C:\\Users\\marcus\\Downloads\\PyQt-gpl-5.3.2\\QtWidgets/sipQtWidgetsQGraphicsGridLayout.cpp"
#line 30 "C:\\Users\\marcus\\Downloads\\PyQt-gpl-5.3.2\\sip/QtWidgets/qsizepolicy.sip"
#include <qsizepolicy.h>
#line 54 "C:\\Users\\marcus\\Downloads\\PyQt-gpl-5.3.2\\QtWidgets/sipQtWidgetsQGraphicsGridLayout.cpp"


class sipQGraphicsGridLayout : public QGraphicsGridLayout
{
public:
    sipQGraphicsGridLayout(QGraphicsLayoutItem*);
    virtual ~sipQGraphicsGridLayout();

    /*
     * There is a public method for every protected method visible from
     * this class.
     */
    void sipProtect_setGraphicsItem(QGraphicsItem*);
    void sipProtect_setOwnedByLayout(bool);
    void sipProtect_addChildLayoutItem(QGraphicsLayoutItem*);

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    void updateGeometry();
    void widgetEvent(QEvent*);
    void getContentsMargins(qreal*,qreal*,qreal*,qreal*) const;
    QSizeF sizeHint(Qt::SizeHint,const QSizeF&) const;
    void setGeometry(const QRectF&);
    void invalidate();
    void removeAt(int);
    QGraphicsLayoutItem* itemAt(int) const;
    int count() const;

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipQGraphicsGridLayout(const sipQGraphicsGridLayout &);
    sipQGraphicsGridLayout &operator = (const sipQGraphicsGridLayout &);

    char sipPyMethods[9];
};

sipQGraphicsGridLayout::sipQGraphicsGridLayout(QGraphicsLayoutItem*a0): QGraphicsGridLayout(a0), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipQGraphicsGridLayout::~sipQGraphicsGridLayout()
{
    sipCommonDtor(sipPySelf);
}

void sipQGraphicsGridLayout::updateGeometry()
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[0],sipPySelf,NULL,sipName_updateGeometry);

    if (!sipMeth)
    {
        QGraphicsGridLayout::updateGeometry();
        return;
    }

    typedef void (*sipVH_QtCore_11)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    ((sipVH_QtCore_11)(sipModuleAPI_QtWidgets_QtCore->em_virthandlers[11]))(sipGILState, 0, sipPySelf, sipMeth);
}

void sipQGraphicsGridLayout::widgetEvent(QEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[1],sipPySelf,NULL,sipName_widgetEvent);

    if (!sipMeth)
    {
        QGraphicsGridLayout::widgetEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_25)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QEvent*);

    ((sipVH_QtCore_25)(sipModuleAPI_QtWidgets_QtCore->em_virthandlers[25]))(sipGILState, 0, sipPySelf, sipMeth, a0);
}

void sipQGraphicsGridLayout::getContentsMargins(qreal*a0,qreal*a1,qreal*a2,qreal*a3) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[2]),sipPySelf,NULL,sipName_getContentsMargins);

    if (!sipMeth)
    {
        QGraphicsGridLayout::getContentsMargins(a0,a1,a2,a3);
        return;
    }

    extern void sipVH_QtWidgets_116(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, double*,double*,double*,double*);

    sipVH_QtWidgets_116(sipGILState, 0, sipPySelf, sipMeth, a0, a1, a2, a3);
}

QSizeF sipQGraphicsGridLayout::sizeHint(Qt::SizeHint a0,const QSizeF& a1) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[3]),sipPySelf,NULL,sipName_sizeHint);

    if (!sipMeth)
        return QGraphicsGridLayout::sizeHint(a0,a1);

    extern QSizeF sipVH_QtWidgets_111(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, Qt::SizeHint,const QSizeF&);

    return sipVH_QtWidgets_111(sipGILState, 0, sipPySelf, sipMeth, a0, a1);
}

void sipQGraphicsGridLayout::setGeometry(const QRectF& a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[4],sipPySelf,NULL,sipName_setGeometry);

    if (!sipMeth)
    {
        QGraphicsGridLayout::setGeometry(a0);
        return;
    }

    typedef void (*sipVH_QtGui_45)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const QRectF&);

    ((sipVH_QtGui_45)(sipModuleAPI_QtWidgets_QtGui->em_virthandlers[45]))(sipGILState, 0, sipPySelf, sipMeth, a0);
}

void sipQGraphicsGridLayout::invalidate()
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[5],sipPySelf,NULL,sipName_invalidate);

    if (!sipMeth)
    {
        QGraphicsGridLayout::invalidate();
        return;
    }

    typedef void (*sipVH_QtCore_11)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    ((sipVH_QtCore_11)(sipModuleAPI_QtWidgets_QtCore->em_virthandlers[11]))(sipGILState, 0, sipPySelf, sipMeth);
}

void sipQGraphicsGridLayout::removeAt(int a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[6],sipPySelf,NULL,sipName_removeAt);

    if (!sipMeth)
    {
        QGraphicsGridLayout::removeAt(a0);
        return;
    }

    typedef void (*sipVH_QtCore_4)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, int);

    ((sipVH_QtCore_4)(sipModuleAPI_QtWidgets_QtCore->em_virthandlers[4]))(sipGILState, 0, sipPySelf, sipMeth, a0);
}

QGraphicsLayoutItem* sipQGraphicsGridLayout::itemAt(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[7]),sipPySelf,NULL,sipName_itemAt);

    if (!sipMeth)
        return QGraphicsGridLayout::itemAt(a0);

    extern QGraphicsLayoutItem* sipVH_QtWidgets_124(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, int);

    return sipVH_QtWidgets_124(sipGILState, 0, sipPySelf, sipMeth, a0);
}

int sipQGraphicsGridLayout::count() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[8]),sipPySelf,NULL,sipName_count);

    if (!sipMeth)
        return QGraphicsGridLayout::count();

    typedef int (*sipVH_QtCore_6)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return ((sipVH_QtCore_6)(sipModuleAPI_QtWidgets_QtCore->em_virthandlers[6]))(sipGILState, 0, sipPySelf, sipMeth);
}

void sipQGraphicsGridLayout::sipProtect_setGraphicsItem(QGraphicsItem*a0)
{
    QGraphicsLayoutItem::setGraphicsItem(a0);
}

void sipQGraphicsGridLayout::sipProtect_setOwnedByLayout(bool a0)
{
    QGraphicsLayoutItem::setOwnedByLayout(a0);
}

void sipQGraphicsGridLayout::sipProtect_addChildLayoutItem(QGraphicsLayoutItem*a0)
{
    QGraphicsLayout::addChildLayoutItem(a0);
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_setGraphicsItem, "QGraphicsGridLayout.setGraphicsItem(QGraphicsItem)");

extern "C" {static PyObject *meth_QGraphicsGridLayout_setGraphicsItem(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_setGraphicsItem(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = NULL;

    {
        QGraphicsItem* a0;
        sipQGraphicsGridLayout *sipCpp;

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, NULL, NULL, "BJ8", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, sipType_QGraphicsItem, &a0))
        {
            sipCpp->sipProtect_setGraphicsItem(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_setGraphicsItem, doc_QGraphicsGridLayout_setGraphicsItem);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_setOwnedByLayout, "QGraphicsGridLayout.setOwnedByLayout(bool)");

extern "C" {static PyObject *meth_QGraphicsGridLayout_setOwnedByLayout(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_setOwnedByLayout(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        sipQGraphicsGridLayout *sipCpp;

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, NULL, NULL, "Bb", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0))
        {
            sipCpp->sipProtect_setOwnedByLayout(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_setOwnedByLayout, doc_QGraphicsGridLayout_setOwnedByLayout);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_addChildLayoutItem, "QGraphicsGridLayout.addChildLayoutItem(QGraphicsLayoutItem)");

extern "C" {static PyObject *meth_QGraphicsGridLayout_addChildLayoutItem(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_addChildLayoutItem(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = NULL;

    {
        QGraphicsLayoutItem* a0;
        sipQGraphicsGridLayout *sipCpp;

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, NULL, NULL, "BJ:", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, sipType_QGraphicsLayoutItem, &a0))
        {
            sipCpp->sipProtect_addChildLayoutItem(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_addChildLayoutItem, doc_QGraphicsGridLayout_addChildLayoutItem);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_addItem, "QGraphicsGridLayout.addItem(QGraphicsLayoutItem, int, int, int, int, Qt.Alignment alignment=0)\n"
    "QGraphicsGridLayout.addItem(QGraphicsLayoutItem, int, int, Qt.Alignment alignment=0)");

extern "C" {static PyObject *meth_QGraphicsGridLayout_addItem(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_addItem(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = NULL;

    {
        QGraphicsLayoutItem* a0;
        int a1;
        int a2;
        int a3;
        int a4;
        Qt::Alignment a5def = 0;
        Qt::Alignment* a5 = &a5def;
        int a5State = 0;
        QGraphicsGridLayout *sipCpp;

        static const char *sipKwdList[] = {
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            sipName_alignment,
        };

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, sipKwdList, NULL, "BJ:iiii|J1", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, sipType_QGraphicsLayoutItem, &a0, &a1, &a2, &a3, &a4, sipType_Qt_Alignment, &a5, &a5State))
        {
            sipCpp->addItem(a0,a1,a2,a3,a4,*a5);
            sipReleaseType(a5,sipType_Qt_Alignment,a5State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    {
        QGraphicsLayoutItem* a0;
        int a1;
        int a2;
        Qt::Alignment a3def = 0;
        Qt::Alignment* a3 = &a3def;
        int a3State = 0;
        sipWrapper *sipOwner = 0;
        QGraphicsGridLayout *sipCpp;

        static const char *sipKwdList[] = {
            NULL,
            NULL,
            NULL,
            sipName_alignment,
        };

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, sipKwdList, NULL, "BJHii|J1", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, sipType_QGraphicsLayoutItem, &a0, &sipOwner, &a1, &a2, sipType_Qt_Alignment, &a3, &a3State))
        {
            sipCpp->addItem(a0,a1,a2,*a3);

            if (sipOwner)
                sipTransferTo(sipSelf, (PyObject *)sipOwner);
            else
                sipTransferBack(sipSelf);
            sipReleaseType(a3,sipType_Qt_Alignment,a3State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_addItem, doc_QGraphicsGridLayout_addItem);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_setHorizontalSpacing, "QGraphicsGridLayout.setHorizontalSpacing(float)");

extern "C" {static PyObject *meth_QGraphicsGridLayout_setHorizontalSpacing(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_setHorizontalSpacing(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        qreal a0;
        QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bd", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0))
        {
            sipCpp->setHorizontalSpacing(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_setHorizontalSpacing, doc_QGraphicsGridLayout_setHorizontalSpacing);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_horizontalSpacing, "QGraphicsGridLayout.horizontalSpacing() -> float");

extern "C" {static PyObject *meth_QGraphicsGridLayout_horizontalSpacing(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_horizontalSpacing(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp))
        {
            qreal sipRes;

            sipRes = sipCpp->horizontalSpacing();

            return PyFloat_FromDouble(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_horizontalSpacing, doc_QGraphicsGridLayout_horizontalSpacing);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_setVerticalSpacing, "QGraphicsGridLayout.setVerticalSpacing(float)");

extern "C" {static PyObject *meth_QGraphicsGridLayout_setVerticalSpacing(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_setVerticalSpacing(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        qreal a0;
        QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bd", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0))
        {
            sipCpp->setVerticalSpacing(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_setVerticalSpacing, doc_QGraphicsGridLayout_setVerticalSpacing);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_verticalSpacing, "QGraphicsGridLayout.verticalSpacing() -> float");

extern "C" {static PyObject *meth_QGraphicsGridLayout_verticalSpacing(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_verticalSpacing(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp))
        {
            qreal sipRes;

            sipRes = sipCpp->verticalSpacing();

            return PyFloat_FromDouble(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_verticalSpacing, doc_QGraphicsGridLayout_verticalSpacing);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_setSpacing, "QGraphicsGridLayout.setSpacing(float)");

extern "C" {static PyObject *meth_QGraphicsGridLayout_setSpacing(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_setSpacing(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        qreal a0;
        QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bd", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0))
        {
            sipCpp->setSpacing(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_setSpacing, doc_QGraphicsGridLayout_setSpacing);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_setRowSpacing, "QGraphicsGridLayout.setRowSpacing(int, float)");

extern "C" {static PyObject *meth_QGraphicsGridLayout_setRowSpacing(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_setRowSpacing(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        qreal a1;
        QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bid", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0, &a1))
        {
            sipCpp->setRowSpacing(a0,a1);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_setRowSpacing, doc_QGraphicsGridLayout_setRowSpacing);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_rowSpacing, "QGraphicsGridLayout.rowSpacing(int) -> float");

extern "C" {static PyObject *meth_QGraphicsGridLayout_rowSpacing(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_rowSpacing(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        const QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0))
        {
            qreal sipRes;

            sipRes = sipCpp->rowSpacing(a0);

            return PyFloat_FromDouble(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_rowSpacing, doc_QGraphicsGridLayout_rowSpacing);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_setColumnSpacing, "QGraphicsGridLayout.setColumnSpacing(int, float)");

extern "C" {static PyObject *meth_QGraphicsGridLayout_setColumnSpacing(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_setColumnSpacing(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        qreal a1;
        QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bid", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0, &a1))
        {
            sipCpp->setColumnSpacing(a0,a1);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_setColumnSpacing, doc_QGraphicsGridLayout_setColumnSpacing);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_columnSpacing, "QGraphicsGridLayout.columnSpacing(int) -> float");

extern "C" {static PyObject *meth_QGraphicsGridLayout_columnSpacing(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_columnSpacing(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        const QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0))
        {
            qreal sipRes;

            sipRes = sipCpp->columnSpacing(a0);

            return PyFloat_FromDouble(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_columnSpacing, doc_QGraphicsGridLayout_columnSpacing);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_setRowStretchFactor, "QGraphicsGridLayout.setRowStretchFactor(int, int)");

extern "C" {static PyObject *meth_QGraphicsGridLayout_setRowStretchFactor(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_setRowStretchFactor(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        int a1;
        QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bii", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0, &a1))
        {
            sipCpp->setRowStretchFactor(a0,a1);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_setRowStretchFactor, doc_QGraphicsGridLayout_setRowStretchFactor);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_rowStretchFactor, "QGraphicsGridLayout.rowStretchFactor(int) -> int");

extern "C" {static PyObject *meth_QGraphicsGridLayout_rowStretchFactor(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_rowStretchFactor(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        const QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0))
        {
            int sipRes;

            sipRes = sipCpp->rowStretchFactor(a0);

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_rowStretchFactor, doc_QGraphicsGridLayout_rowStretchFactor);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_setColumnStretchFactor, "QGraphicsGridLayout.setColumnStretchFactor(int, int)");

extern "C" {static PyObject *meth_QGraphicsGridLayout_setColumnStretchFactor(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_setColumnStretchFactor(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        int a1;
        QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bii", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0, &a1))
        {
            sipCpp->setColumnStretchFactor(a0,a1);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_setColumnStretchFactor, doc_QGraphicsGridLayout_setColumnStretchFactor);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_columnStretchFactor, "QGraphicsGridLayout.columnStretchFactor(int) -> int");

extern "C" {static PyObject *meth_QGraphicsGridLayout_columnStretchFactor(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_columnStretchFactor(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        const QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0))
        {
            int sipRes;

            sipRes = sipCpp->columnStretchFactor(a0);

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_columnStretchFactor, doc_QGraphicsGridLayout_columnStretchFactor);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_setRowMinimumHeight, "QGraphicsGridLayout.setRowMinimumHeight(int, float)");

extern "C" {static PyObject *meth_QGraphicsGridLayout_setRowMinimumHeight(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_setRowMinimumHeight(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        qreal a1;
        QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bid", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0, &a1))
        {
            sipCpp->setRowMinimumHeight(a0,a1);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_setRowMinimumHeight, doc_QGraphicsGridLayout_setRowMinimumHeight);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_rowMinimumHeight, "QGraphicsGridLayout.rowMinimumHeight(int) -> float");

extern "C" {static PyObject *meth_QGraphicsGridLayout_rowMinimumHeight(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_rowMinimumHeight(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        const QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0))
        {
            qreal sipRes;

            sipRes = sipCpp->rowMinimumHeight(a0);

            return PyFloat_FromDouble(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_rowMinimumHeight, doc_QGraphicsGridLayout_rowMinimumHeight);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_setRowPreferredHeight, "QGraphicsGridLayout.setRowPreferredHeight(int, float)");

extern "C" {static PyObject *meth_QGraphicsGridLayout_setRowPreferredHeight(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_setRowPreferredHeight(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        qreal a1;
        QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bid", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0, &a1))
        {
            sipCpp->setRowPreferredHeight(a0,a1);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_setRowPreferredHeight, doc_QGraphicsGridLayout_setRowPreferredHeight);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_rowPreferredHeight, "QGraphicsGridLayout.rowPreferredHeight(int) -> float");

extern "C" {static PyObject *meth_QGraphicsGridLayout_rowPreferredHeight(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_rowPreferredHeight(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        const QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0))
        {
            qreal sipRes;

            sipRes = sipCpp->rowPreferredHeight(a0);

            return PyFloat_FromDouble(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_rowPreferredHeight, doc_QGraphicsGridLayout_rowPreferredHeight);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_setRowMaximumHeight, "QGraphicsGridLayout.setRowMaximumHeight(int, float)");

extern "C" {static PyObject *meth_QGraphicsGridLayout_setRowMaximumHeight(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_setRowMaximumHeight(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        qreal a1;
        QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bid", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0, &a1))
        {
            sipCpp->setRowMaximumHeight(a0,a1);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_setRowMaximumHeight, doc_QGraphicsGridLayout_setRowMaximumHeight);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_rowMaximumHeight, "QGraphicsGridLayout.rowMaximumHeight(int) -> float");

extern "C" {static PyObject *meth_QGraphicsGridLayout_rowMaximumHeight(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_rowMaximumHeight(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        const QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0))
        {
            qreal sipRes;

            sipRes = sipCpp->rowMaximumHeight(a0);

            return PyFloat_FromDouble(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_rowMaximumHeight, doc_QGraphicsGridLayout_rowMaximumHeight);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_setRowFixedHeight, "QGraphicsGridLayout.setRowFixedHeight(int, float)");

extern "C" {static PyObject *meth_QGraphicsGridLayout_setRowFixedHeight(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_setRowFixedHeight(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        qreal a1;
        QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bid", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0, &a1))
        {
            sipCpp->setRowFixedHeight(a0,a1);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_setRowFixedHeight, doc_QGraphicsGridLayout_setRowFixedHeight);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_setColumnMinimumWidth, "QGraphicsGridLayout.setColumnMinimumWidth(int, float)");

extern "C" {static PyObject *meth_QGraphicsGridLayout_setColumnMinimumWidth(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_setColumnMinimumWidth(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        qreal a1;
        QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bid", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0, &a1))
        {
            sipCpp->setColumnMinimumWidth(a0,a1);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_setColumnMinimumWidth, doc_QGraphicsGridLayout_setColumnMinimumWidth);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_columnMinimumWidth, "QGraphicsGridLayout.columnMinimumWidth(int) -> float");

extern "C" {static PyObject *meth_QGraphicsGridLayout_columnMinimumWidth(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_columnMinimumWidth(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        const QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0))
        {
            qreal sipRes;

            sipRes = sipCpp->columnMinimumWidth(a0);

            return PyFloat_FromDouble(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_columnMinimumWidth, doc_QGraphicsGridLayout_columnMinimumWidth);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_setColumnPreferredWidth, "QGraphicsGridLayout.setColumnPreferredWidth(int, float)");

extern "C" {static PyObject *meth_QGraphicsGridLayout_setColumnPreferredWidth(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_setColumnPreferredWidth(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        qreal a1;
        QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bid", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0, &a1))
        {
            sipCpp->setColumnPreferredWidth(a0,a1);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_setColumnPreferredWidth, doc_QGraphicsGridLayout_setColumnPreferredWidth);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_columnPreferredWidth, "QGraphicsGridLayout.columnPreferredWidth(int) -> float");

extern "C" {static PyObject *meth_QGraphicsGridLayout_columnPreferredWidth(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_columnPreferredWidth(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        const QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0))
        {
            qreal sipRes;

            sipRes = sipCpp->columnPreferredWidth(a0);

            return PyFloat_FromDouble(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_columnPreferredWidth, doc_QGraphicsGridLayout_columnPreferredWidth);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_setColumnMaximumWidth, "QGraphicsGridLayout.setColumnMaximumWidth(int, float)");

extern "C" {static PyObject *meth_QGraphicsGridLayout_setColumnMaximumWidth(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_setColumnMaximumWidth(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        qreal a1;
        QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bid", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0, &a1))
        {
            sipCpp->setColumnMaximumWidth(a0,a1);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_setColumnMaximumWidth, doc_QGraphicsGridLayout_setColumnMaximumWidth);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_columnMaximumWidth, "QGraphicsGridLayout.columnMaximumWidth(int) -> float");

extern "C" {static PyObject *meth_QGraphicsGridLayout_columnMaximumWidth(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_columnMaximumWidth(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        const QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0))
        {
            qreal sipRes;

            sipRes = sipCpp->columnMaximumWidth(a0);

            return PyFloat_FromDouble(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_columnMaximumWidth, doc_QGraphicsGridLayout_columnMaximumWidth);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_setColumnFixedWidth, "QGraphicsGridLayout.setColumnFixedWidth(int, float)");

extern "C" {static PyObject *meth_QGraphicsGridLayout_setColumnFixedWidth(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_setColumnFixedWidth(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        qreal a1;
        QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bid", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0, &a1))
        {
            sipCpp->setColumnFixedWidth(a0,a1);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_setColumnFixedWidth, doc_QGraphicsGridLayout_setColumnFixedWidth);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_setRowAlignment, "QGraphicsGridLayout.setRowAlignment(int, Qt.Alignment)");

extern "C" {static PyObject *meth_QGraphicsGridLayout_setRowAlignment(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_setRowAlignment(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        Qt::Alignment* a1;
        int a1State = 0;
        QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BiJ1", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0, sipType_Qt_Alignment, &a1, &a1State))
        {
            sipCpp->setRowAlignment(a0,*a1);
            sipReleaseType(a1,sipType_Qt_Alignment,a1State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_setRowAlignment, doc_QGraphicsGridLayout_setRowAlignment);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_rowAlignment, "QGraphicsGridLayout.rowAlignment(int) -> Qt.Alignment");

extern "C" {static PyObject *meth_QGraphicsGridLayout_rowAlignment(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_rowAlignment(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        const QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0))
        {
            Qt::Alignment*sipRes;

            sipRes = new Qt::Alignment(sipCpp->rowAlignment(a0));

            return sipConvertFromNewType(sipRes,sipType_Qt_Alignment,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_rowAlignment, doc_QGraphicsGridLayout_rowAlignment);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_setColumnAlignment, "QGraphicsGridLayout.setColumnAlignment(int, Qt.Alignment)");

extern "C" {static PyObject *meth_QGraphicsGridLayout_setColumnAlignment(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_setColumnAlignment(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        Qt::Alignment* a1;
        int a1State = 0;
        QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BiJ1", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0, sipType_Qt_Alignment, &a1, &a1State))
        {
            sipCpp->setColumnAlignment(a0,*a1);
            sipReleaseType(a1,sipType_Qt_Alignment,a1State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_setColumnAlignment, doc_QGraphicsGridLayout_setColumnAlignment);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_columnAlignment, "QGraphicsGridLayout.columnAlignment(int) -> Qt.Alignment");

extern "C" {static PyObject *meth_QGraphicsGridLayout_columnAlignment(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_columnAlignment(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        const QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0))
        {
            Qt::Alignment*sipRes;

            sipRes = new Qt::Alignment(sipCpp->columnAlignment(a0));

            return sipConvertFromNewType(sipRes,sipType_Qt_Alignment,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_columnAlignment, doc_QGraphicsGridLayout_columnAlignment);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_setAlignment, "QGraphicsGridLayout.setAlignment(QGraphicsLayoutItem, Qt.Alignment)");

extern "C" {static PyObject *meth_QGraphicsGridLayout_setAlignment(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_setAlignment(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QGraphicsLayoutItem* a0;
        Qt::Alignment* a1;
        int a1State = 0;
        QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ8J1", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, sipType_QGraphicsLayoutItem, &a0, sipType_Qt_Alignment, &a1, &a1State))
        {
            sipCpp->setAlignment(a0,*a1);
            sipReleaseType(a1,sipType_Qt_Alignment,a1State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_setAlignment, doc_QGraphicsGridLayout_setAlignment);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_alignment, "QGraphicsGridLayout.alignment(QGraphicsLayoutItem) -> Qt.Alignment");

extern "C" {static PyObject *meth_QGraphicsGridLayout_alignment(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_alignment(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QGraphicsLayoutItem* a0;
        const QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ8", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, sipType_QGraphicsLayoutItem, &a0))
        {
            Qt::Alignment*sipRes;

            sipRes = new Qt::Alignment(sipCpp->alignment(a0));

            return sipConvertFromNewType(sipRes,sipType_Qt_Alignment,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_alignment, doc_QGraphicsGridLayout_alignment);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_rowCount, "QGraphicsGridLayout.rowCount() -> int");

extern "C" {static PyObject *meth_QGraphicsGridLayout_rowCount(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_rowCount(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp))
        {
            int sipRes;

            sipRes = sipCpp->rowCount();

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_rowCount, doc_QGraphicsGridLayout_rowCount);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_columnCount, "QGraphicsGridLayout.columnCount() -> int");

extern "C" {static PyObject *meth_QGraphicsGridLayout_columnCount(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_columnCount(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp))
        {
            int sipRes;

            sipRes = sipCpp->columnCount();

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_columnCount, doc_QGraphicsGridLayout_columnCount);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_itemAt, "QGraphicsGridLayout.itemAt(int, int) -> QGraphicsLayoutItem\n"
    "QGraphicsGridLayout.itemAt(int) -> QGraphicsLayoutItem");

extern "C" {static PyObject *meth_QGraphicsGridLayout_itemAt(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_itemAt(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        int a0;
        int a1;
        const QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bii", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0, &a1))
        {
            QGraphicsLayoutItem*sipRes;

            sipRes = sipCpp->itemAt(a0,a1);

            return sipConvertFromType(sipRes,sipType_QGraphicsLayoutItem,NULL);
        }
    }

    {
        int a0;
        const QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0))
        {
            QGraphicsLayoutItem*sipRes;

            sipRes = (sipSelfWasArg ? sipCpp->QGraphicsGridLayout::itemAt(a0) : sipCpp->itemAt(a0));

            return sipConvertFromType(sipRes,sipType_QGraphicsLayoutItem,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_itemAt, doc_QGraphicsGridLayout_itemAt);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_count, "QGraphicsGridLayout.count() -> int");

extern "C" {static PyObject *meth_QGraphicsGridLayout_count(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_count(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        const QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp))
        {
            int sipRes;

            sipRes = (sipSelfWasArg ? sipCpp->QGraphicsGridLayout::count() : sipCpp->count());

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_count, doc_QGraphicsGridLayout_count);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_removeAt, "QGraphicsGridLayout.removeAt(int)");

extern "C" {static PyObject *meth_QGraphicsGridLayout_removeAt(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_removeAt(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        int a0;
        QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, &a0))
        {
#line 74 "C:\\Users\\marcus\\Downloads\\PyQt-gpl-5.3.2\\sip/QtWidgets/qgraphicsgridlayout.sip"
        // The ownership of any existing item must be passed back to Python.
        QGraphicsLayoutItem *itm;
        
        if (a0 < sipCpp->count())
            itm = sipCpp->itemAt(a0);
        else
            itm = 0;
        
        Py_BEGIN_ALLOW_THREADS
        sipSelfWasArg ? sipCpp->QGraphicsGridLayout::removeAt(a0)
                      : sipCpp->removeAt(a0);
        Py_END_ALLOW_THREADS
        
        if (itm)
        {
            PyObject *itmo = sipGetPyObject(itm, sipType_QGraphicsLayoutItem);
        
            if (itmo)
                sipTransferBack(itmo);
        }
#line 1520 "C:\\Users\\marcus\\Downloads\\PyQt-gpl-5.3.2\\QtWidgets/sipQtWidgetsQGraphicsGridLayout.cpp"

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_removeAt, doc_QGraphicsGridLayout_removeAt);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_invalidate, "QGraphicsGridLayout.invalidate()");

extern "C" {static PyObject *meth_QGraphicsGridLayout_invalidate(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_invalidate(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp))
        {
            (sipSelfWasArg ? sipCpp->QGraphicsGridLayout::invalidate() : sipCpp->invalidate());

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_invalidate, doc_QGraphicsGridLayout_invalidate);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_setGeometry, "QGraphicsGridLayout.setGeometry(QRectF)");

extern "C" {static PyObject *meth_QGraphicsGridLayout_setGeometry(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_setGeometry(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        const QRectF* a0;
        QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, sipType_QRectF, &a0))
        {
            (sipSelfWasArg ? sipCpp->QGraphicsGridLayout::setGeometry(*a0) : sipCpp->setGeometry(*a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_setGeometry, doc_QGraphicsGridLayout_setGeometry);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_sizeHint, "QGraphicsGridLayout.sizeHint(Qt.SizeHint, QSizeF constraint=QSizeF()) -> QSizeF");

extern "C" {static PyObject *meth_QGraphicsGridLayout_sizeHint(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_sizeHint(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        Qt::SizeHint a0;
        const QSizeF& a1def = QSizeF();
        const QSizeF* a1 = &a1def;
        const QGraphicsGridLayout *sipCpp;

        static const char *sipKwdList[] = {
            NULL,
            sipName_constraint,
        };

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, sipKwdList, NULL, "BE|J9", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, sipType_Qt_SizeHint, &a0, sipType_QSizeF, &a1))
        {
            QSizeF*sipRes;

            sipRes = new QSizeF((sipSelfWasArg ? sipCpp->QGraphicsGridLayout::sizeHint(a0,*a1) : sipCpp->sizeHint(a0,*a1)));

            return sipConvertFromNewType(sipRes,sipType_QSizeF,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_sizeHint, doc_QGraphicsGridLayout_sizeHint);

    return NULL;
}


PyDoc_STRVAR(doc_QGraphicsGridLayout_removeItem, "QGraphicsGridLayout.removeItem(QGraphicsLayoutItem)");

extern "C" {static PyObject *meth_QGraphicsGridLayout_removeItem(PyObject *, PyObject *);}
static PyObject *meth_QGraphicsGridLayout_removeItem(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QGraphicsLayoutItem* a0;
        QGraphicsGridLayout *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ<", &sipSelf, sipType_QGraphicsGridLayout, &sipCpp, sipType_QGraphicsLayoutItem, &a0))
        {
            sipCpp->removeItem(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QGraphicsGridLayout, sipName_removeItem, doc_QGraphicsGridLayout_removeItem);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QGraphicsGridLayout(void *, const sipTypeDef *);}
static void *cast_QGraphicsGridLayout(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_QGraphicsGridLayout)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_QGraphicsLayout)->ctd_cast((QGraphicsLayout *)(QGraphicsGridLayout *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QGraphicsGridLayout(void *, int);}
static void release_QGraphicsGridLayout(void *sipCppV,int sipState)
{
    if (sipState & SIP_DERIVED_CLASS)
        delete reinterpret_cast<sipQGraphicsGridLayout *>(sipCppV);
    else
        delete reinterpret_cast<QGraphicsGridLayout *>(sipCppV);
}


extern "C" {static void dealloc_QGraphicsGridLayout(sipSimpleWrapper *);}
static void dealloc_QGraphicsGridLayout(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerived(sipSelf))
        reinterpret_cast<sipQGraphicsGridLayout *>(sipGetAddress(sipSelf))->sipPySelf = NULL;

    if (sipIsPyOwned(sipSelf))
    {
        release_QGraphicsGridLayout(sipGetAddress(sipSelf),sipSelf->flags);
    }
}


extern "C" {static void *init_type_QGraphicsGridLayout(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_QGraphicsGridLayout(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **sipOwner, PyObject **sipParseErr)
{
    sipQGraphicsGridLayout *sipCpp = 0;

    {
        QGraphicsLayoutItem* a0 = 0;

        static const char *sipKwdList[] = {
            sipName_parent,
        };

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, sipKwdList, sipUnused, "|JH", sipType_QGraphicsLayoutItem, &a0, sipOwner))
        {
            sipCpp = new sipQGraphicsGridLayout(a0);

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QGraphicsGridLayout[] = {{128, 255, 1}};


static PyMethodDef methods_QGraphicsGridLayout[] = {
    {SIP_MLNAME_CAST(sipName_addChildLayoutItem), (PyCFunction)meth_QGraphicsGridLayout_addChildLayoutItem, METH_VARARGS|METH_KEYWORDS, NULL},
    {SIP_MLNAME_CAST(sipName_addItem), (PyCFunction)meth_QGraphicsGridLayout_addItem, METH_VARARGS|METH_KEYWORDS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_addItem)},
    {SIP_MLNAME_CAST(sipName_alignment), meth_QGraphicsGridLayout_alignment, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_alignment)},
    {SIP_MLNAME_CAST(sipName_columnAlignment), meth_QGraphicsGridLayout_columnAlignment, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_columnAlignment)},
    {SIP_MLNAME_CAST(sipName_columnCount), meth_QGraphicsGridLayout_columnCount, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_columnCount)},
    {SIP_MLNAME_CAST(sipName_columnMaximumWidth), meth_QGraphicsGridLayout_columnMaximumWidth, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_columnMaximumWidth)},
    {SIP_MLNAME_CAST(sipName_columnMinimumWidth), meth_QGraphicsGridLayout_columnMinimumWidth, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_columnMinimumWidth)},
    {SIP_MLNAME_CAST(sipName_columnPreferredWidth), meth_QGraphicsGridLayout_columnPreferredWidth, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_columnPreferredWidth)},
    {SIP_MLNAME_CAST(sipName_columnSpacing), meth_QGraphicsGridLayout_columnSpacing, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_columnSpacing)},
    {SIP_MLNAME_CAST(sipName_columnStretchFactor), meth_QGraphicsGridLayout_columnStretchFactor, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_columnStretchFactor)},
    {SIP_MLNAME_CAST(sipName_count), meth_QGraphicsGridLayout_count, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_count)},
    {SIP_MLNAME_CAST(sipName_horizontalSpacing), meth_QGraphicsGridLayout_horizontalSpacing, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_horizontalSpacing)},
    {SIP_MLNAME_CAST(sipName_invalidate), meth_QGraphicsGridLayout_invalidate, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_invalidate)},
    {SIP_MLNAME_CAST(sipName_itemAt), meth_QGraphicsGridLayout_itemAt, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_itemAt)},
    {SIP_MLNAME_CAST(sipName_removeAt), meth_QGraphicsGridLayout_removeAt, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_removeAt)},
    {SIP_MLNAME_CAST(sipName_removeItem), meth_QGraphicsGridLayout_removeItem, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_removeItem)},
    {SIP_MLNAME_CAST(sipName_rowAlignment), meth_QGraphicsGridLayout_rowAlignment, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_rowAlignment)},
    {SIP_MLNAME_CAST(sipName_rowCount), meth_QGraphicsGridLayout_rowCount, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_rowCount)},
    {SIP_MLNAME_CAST(sipName_rowMaximumHeight), meth_QGraphicsGridLayout_rowMaximumHeight, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_rowMaximumHeight)},
    {SIP_MLNAME_CAST(sipName_rowMinimumHeight), meth_QGraphicsGridLayout_rowMinimumHeight, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_rowMinimumHeight)},
    {SIP_MLNAME_CAST(sipName_rowPreferredHeight), meth_QGraphicsGridLayout_rowPreferredHeight, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_rowPreferredHeight)},
    {SIP_MLNAME_CAST(sipName_rowSpacing), meth_QGraphicsGridLayout_rowSpacing, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_rowSpacing)},
    {SIP_MLNAME_CAST(sipName_rowStretchFactor), meth_QGraphicsGridLayout_rowStretchFactor, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_rowStretchFactor)},
    {SIP_MLNAME_CAST(sipName_setAlignment), meth_QGraphicsGridLayout_setAlignment, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_setAlignment)},
    {SIP_MLNAME_CAST(sipName_setColumnAlignment), meth_QGraphicsGridLayout_setColumnAlignment, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_setColumnAlignment)},
    {SIP_MLNAME_CAST(sipName_setColumnFixedWidth), meth_QGraphicsGridLayout_setColumnFixedWidth, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_setColumnFixedWidth)},
    {SIP_MLNAME_CAST(sipName_setColumnMaximumWidth), meth_QGraphicsGridLayout_setColumnMaximumWidth, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_setColumnMaximumWidth)},
    {SIP_MLNAME_CAST(sipName_setColumnMinimumWidth), meth_QGraphicsGridLayout_setColumnMinimumWidth, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_setColumnMinimumWidth)},
    {SIP_MLNAME_CAST(sipName_setColumnPreferredWidth), meth_QGraphicsGridLayout_setColumnPreferredWidth, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_setColumnPreferredWidth)},
    {SIP_MLNAME_CAST(sipName_setColumnSpacing), meth_QGraphicsGridLayout_setColumnSpacing, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_setColumnSpacing)},
    {SIP_MLNAME_CAST(sipName_setColumnStretchFactor), meth_QGraphicsGridLayout_setColumnStretchFactor, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_setColumnStretchFactor)},
    {SIP_MLNAME_CAST(sipName_setGeometry), meth_QGraphicsGridLayout_setGeometry, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_setGeometry)},
    {SIP_MLNAME_CAST(sipName_setGraphicsItem), (PyCFunction)meth_QGraphicsGridLayout_setGraphicsItem, METH_VARARGS|METH_KEYWORDS, NULL},
    {SIP_MLNAME_CAST(sipName_setHorizontalSpacing), meth_QGraphicsGridLayout_setHorizontalSpacing, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_setHorizontalSpacing)},
    {SIP_MLNAME_CAST(sipName_setOwnedByLayout), (PyCFunction)meth_QGraphicsGridLayout_setOwnedByLayout, METH_VARARGS|METH_KEYWORDS, NULL},
    {SIP_MLNAME_CAST(sipName_setRowAlignment), meth_QGraphicsGridLayout_setRowAlignment, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_setRowAlignment)},
    {SIP_MLNAME_CAST(sipName_setRowFixedHeight), meth_QGraphicsGridLayout_setRowFixedHeight, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_setRowFixedHeight)},
    {SIP_MLNAME_CAST(sipName_setRowMaximumHeight), meth_QGraphicsGridLayout_setRowMaximumHeight, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_setRowMaximumHeight)},
    {SIP_MLNAME_CAST(sipName_setRowMinimumHeight), meth_QGraphicsGridLayout_setRowMinimumHeight, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_setRowMinimumHeight)},
    {SIP_MLNAME_CAST(sipName_setRowPreferredHeight), meth_QGraphicsGridLayout_setRowPreferredHeight, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_setRowPreferredHeight)},
    {SIP_MLNAME_CAST(sipName_setRowSpacing), meth_QGraphicsGridLayout_setRowSpacing, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_setRowSpacing)},
    {SIP_MLNAME_CAST(sipName_setRowStretchFactor), meth_QGraphicsGridLayout_setRowStretchFactor, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_setRowStretchFactor)},
    {SIP_MLNAME_CAST(sipName_setSpacing), meth_QGraphicsGridLayout_setSpacing, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_setSpacing)},
    {SIP_MLNAME_CAST(sipName_setVerticalSpacing), meth_QGraphicsGridLayout_setVerticalSpacing, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_setVerticalSpacing)},
    {SIP_MLNAME_CAST(sipName_sizeHint), (PyCFunction)meth_QGraphicsGridLayout_sizeHint, METH_VARARGS|METH_KEYWORDS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_sizeHint)},
    {SIP_MLNAME_CAST(sipName_verticalSpacing), meth_QGraphicsGridLayout_verticalSpacing, METH_VARARGS, SIP_MLDOC_CAST(doc_QGraphicsGridLayout_verticalSpacing)}
};

PyDoc_STRVAR(doc_QGraphicsGridLayout, "\1QGraphicsGridLayout(QGraphicsLayoutItem parent=None)");


pyqt5ClassTypeDef sipTypeDef_QtWidgets_QGraphicsGridLayout = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_SUPER_INIT|SIP_TYPE_CLASS,
        sipNameNr_QGraphicsGridLayout,
        {0}
    },
    {
        sipNameNr_QGraphicsGridLayout,
        {0, 0, 1},
        46, methods_QGraphicsGridLayout,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_QGraphicsGridLayout,
    -1,
    -1,
    supers_QGraphicsGridLayout,
    0,
    init_type_QGraphicsGridLayout,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QGraphicsGridLayout,
    0,
    0,
    0,
    release_QGraphicsGridLayout,
    cast_QGraphicsGridLayout,
    0,
    0,
    0,
    0,
    0,
    0
},
    0,
    0,
    0,
    0
};
