QT.script_private.VERSION = 5.4.0
QT.script_private.MAJOR_VERSION = 5
QT.script_private.MINOR_VERSION = 4
QT.script_private.PATCH_VERSION = 0
QT.script_private.name = QtScript
QT.script_private.libs = $$QT_MODULE_LIB_BASE
QT.script_private.includes = $$QT_MODULE_INCLUDE_BASE/QtScript/5.4.0 $$QT_MODULE_INCLUDE_BASE/QtScript/5.4.0/QtScript
QT.script_private.depends = script
QT.script_private.module_config = internal_module no_link
