QT.sql_private.VERSION = 5.4.0
QT.sql_private.MAJOR_VERSION = 5
QT.sql_private.MINOR_VERSION = 4
QT.sql_private.PATCH_VERSION = 0
QT.sql_private.name = QtSql
QT.sql_private.libs = $$QT_MODULE_LIB_BASE
QT.sql_private.includes = $$QT_MODULE_INCLUDE_BASE/QtSql/5.4.0 $$QT_MODULE_INCLUDE_BASE/QtSql/5.4.0/QtSql
QT.sql_private.depends = sql
QT.sql_private.module_config = internal_module no_link
