QT.axbase_private.VERSION = 5.4.0
QT.axbase_private.MAJOR_VERSION = 5
QT.axbase_private.MINOR_VERSION = 4
QT.axbase_private.PATCH_VERSION = 0
QT.axbase_private.name = QtAxBase
QT.axbase_private.libs = $$QT_MODULE_LIB_BASE
QT.axbase_private.includes = $$QT_MODULE_INCLUDE_BASE/ActiveQt/5.4.0 $$QT_MODULE_INCLUDE_BASE/ActiveQt/5.4.0/ActiveQt
QT.axbase_private.depends = axbase
QT.axbase_private.module_config = staticlib internal_module no_link
