QT.scripttools_private.VERSION = 5.4.0
QT.scripttools_private.MAJOR_VERSION = 5
QT.scripttools_private.MINOR_VERSION = 4
QT.scripttools_private.PATCH_VERSION = 0
QT.scripttools_private.name = QtScriptTools
QT.scripttools_private.libs = $$QT_MODULE_LIB_BASE
QT.scripttools_private.includes = $$QT_MODULE_INCLUDE_BASE/QtScriptTools/5.4.0 $$QT_MODULE_INCLUDE_BASE/QtScriptTools/5.4.0/QtScriptTools
QT.scripttools_private.depends = scripttools
QT.scripttools_private.module_config = internal_module no_link
