QT.svg_private.VERSION = 5.4.0
QT.svg_private.MAJOR_VERSION = 5
QT.svg_private.MINOR_VERSION = 4
QT.svg_private.PATCH_VERSION = 0
QT.svg_private.name = QtSvg
QT.svg_private.libs = $$QT_MODULE_LIB_BASE
QT.svg_private.includes = $$QT_MODULE_INCLUDE_BASE/QtSvg/5.4.0 $$QT_MODULE_INCLUDE_BASE/QtSvg/5.4.0/QtSvg
QT.svg_private.depends = svg
QT.svg_private.module_config = internal_module no_link
