QT.sensors_private.VERSION = 5.4.0
QT.sensors_private.MAJOR_VERSION = 5
QT.sensors_private.MINOR_VERSION = 4
QT.sensors_private.PATCH_VERSION = 0
QT.sensors_private.name = QtSensors
QT.sensors_private.libs = $$QT_MODULE_LIB_BASE
QT.sensors_private.includes = $$QT_MODULE_INCLUDE_BASE/QtSensors/5.4.0 $$QT_MODULE_INCLUDE_BASE/QtSensors/5.4.0/QtSensors
QT.sensors_private.depends = sensors
QT.sensors_private.module_config = internal_module no_link
