QT.designer_private.VERSION = 5.4.0
QT.designer_private.MAJOR_VERSION = 5
QT.designer_private.MINOR_VERSION = 4
QT.designer_private.PATCH_VERSION = 0
QT.designer_private.name = QtDesigner
QT.designer_private.libs = $$QT_MODULE_LIB_BASE
QT.designer_private.includes = $$QT_MODULE_INCLUDE_BASE/QtDesigner/5.4.0 $$QT_MODULE_INCLUDE_BASE/QtDesigner/5.4.0/QtDesigner
QT.designer_private.depends = designer
QT.designer_private.module_config = internal_module no_link
