QT.uitools_private.VERSION = 5.4.0
QT.uitools_private.MAJOR_VERSION = 5
QT.uitools_private.MINOR_VERSION = 4
QT.uitools_private.PATCH_VERSION = 0
QT.uitools_private.name = QtUiTools
QT.uitools_private.libs = $$QT_MODULE_LIB_BASE
QT.uitools_private.includes = $$QT_MODULE_INCLUDE_BASE/QtUiTools/5.4.0 $$QT_MODULE_INCLUDE_BASE/QtUiTools/5.4.0/QtUiTools
QT.uitools_private.depends = uitools
QT.uitools_private.module_config = staticlib internal_module no_link
