QT.webchannel_private.VERSION = 5.4.0
QT.webchannel_private.MAJOR_VERSION = 5
QT.webchannel_private.MINOR_VERSION = 4
QT.webchannel_private.PATCH_VERSION = 0
QT.webchannel_private.name = QtWebChannel
QT.webchannel_private.libs = $$QT_MODULE_LIB_BASE
QT.webchannel_private.includes = $$QT_MODULE_INCLUDE_BASE/QtWebChannel/5.4.0 $$QT_MODULE_INCLUDE_BASE/QtWebChannel/5.4.0/QtWebChannel
QT.webchannel_private.depends = webchannel
QT.webchannel_private.module_config = internal_module no_link
