QT.webkitwidgets_private.VERSION = 5.4.0
QT.webkitwidgets_private.MAJOR_VERSION = 5
QT.webkitwidgets_private.MINOR_VERSION = 4
QT.webkitwidgets_private.PATCH_VERSION = 0
QT.webkitwidgets_private.name = QtWebKitWidgets
QT.webkitwidgets_private.libs = $$QT_MODULE_LIB_BASE
QT.webkitwidgets_private.includes = $$QT_MODULE_INCLUDE_BASE/QtWebKitWidgets/5.4.0 $$QT_MODULE_INCLUDE_BASE/QtWebKitWidgets/5.4.0/QtWebKitWidgets
QT.webkitwidgets_private.depends = webkitwidgets
QT.webkitwidgets_private.module_config = internal_module no_link
