QT.location_private.VERSION = 5.4.0
QT.location_private.MAJOR_VERSION = 5
QT.location_private.MINOR_VERSION = 4
QT.location_private.PATCH_VERSION = 0
QT.location_private.name = QtLocation
QT.location_private.libs = $$QT_MODULE_LIB_BASE
QT.location_private.includes = $$QT_MODULE_INCLUDE_BASE/QtLocation/5.4.0 $$QT_MODULE_INCLUDE_BASE/QtLocation/5.4.0/QtLocation
QT.location_private.depends = location
QT.location_private.module_config = internal_module no_link
