QT.winextras_private.VERSION = 5.4.0
QT.winextras_private.MAJOR_VERSION = 5
QT.winextras_private.MINOR_VERSION = 4
QT.winextras_private.PATCH_VERSION = 0
QT.winextras_private.name = QtWinExtras
QT.winextras_private.libs = $$QT_MODULE_LIB_BASE
QT.winextras_private.includes = $$QT_MODULE_INCLUDE_BASE/QtWinExtras/5.4.0 $$QT_MODULE_INCLUDE_BASE/QtWinExtras/5.4.0/QtWinExtras
QT.winextras_private.depends = winextras
QT.winextras_private.module_config = internal_module no_link
