QT.webkit_private.VERSION = 5.4.0
QT.webkit_private.MAJOR_VERSION = 5
QT.webkit_private.MINOR_VERSION = 4
QT.webkit_private.PATCH_VERSION = 0
QT.webkit_private.name = QtWebKit
QT.webkit_private.libs = $$QT_MODULE_LIB_BASE
QT.webkit_private.includes = $$QT_MODULE_INCLUDE_BASE/QtWebKit/5.4.0 $$QT_MODULE_INCLUDE_BASE/QtWebKit/5.4.0/QtWebKit
QT.webkit_private.depends = webkit
QT.webkit_private.module_config = internal_module no_link
